### ISSUE TITLE
Does not seem to respect .lein/profiles.clj plugins

### ISSUE THREAD

**Issue by sooheon** [luminus-framework/luminus-nrepl#3]
Trying to connect to the nrepl port started automatically by luminus on port 7000 with emacs' cider, I get errors that cider-nrepl and refactor-nrepl are not installed. Normally, I added these deps to my lein profile (under :user). 

I have also tried adding the relevant plugins under `:project/dev`, as well as `profiles/dev` (in the luminus project.clj). Neither seem to work. Is this because luminus-nrepl simply starts the nrepl with the three `:dependencies` in this repo?

**Comment by yogthos** [comment]
I would've expected that the final dependencies that get resolved by lein would be used at runtime, but I haven't really explored this as I don't use emacs myself.

**Comment by yogthos** [comment]
Actually, your problem might be that you don't have the cider middleware included. You can add it in `env/dev/clj/<app-name>/dev_middleware.clj` for development or right in the `<app-name>.middleware` namespace if you want it for prod as well.

**Comment by j0ni** [comment]
It's nrepl middleware you want to add, not ring middleware. You can add that as described in the [`cider-nrepl` readme](https://github.com/clojure-emacs/cider-nrepl#via-embedding-nrepl-in-your-app) like so:

``` clojure
(nrepl-server/start-server :port 7888 :handler cider-nrepl-handler))
```

It looks like the `luminus.repl-server/start` function config map takes a `:handler` key that gets passed straight in, so that should work.

**Comment by yogthos** [comment]
@sooheon could you confirm if that works?

**Comment by sooheon** [comment]
@yogthos yes, I can confirm @j0ni's method of passing the cider-nrepl-handler in works. Still, it doesn't seem ideal, when you should be able to declaratively add plugins/dependencies in the project definition. For example, the above method works for cider-nrepl, but doesn't for refactor-nrepl, which should normally just be added to the `:plugins` key. Isn't the issue that the luminus-nrepl, when starting, only has its basic dependencies, and doesn't merge in from the main project def?

**Comment by yogthos** [comment]
This library isn't a plugin itself, but part of the app so it wouldn't have access to project def. I don't think the functionality you're looking for is possible with this approach.

**Comment by sooheon** [comment]
Ok, I see. I suppose if I really want my cider middlewares, I should just jack into a new nrepl server. Thanks.

**Comment by j0ni** [comment]
@sooheon I think you should be able to compose the 2 middlewares and add them via handler. I'm not near a computer to try that though. 

Fwiw I think it's a bit iffy running `refactor-nrepl` in a production environment. I spent an afternoon last week staring at thread dumps before finding that it was responsible for pegging my laptop at ~40% while my app was idling.
