### ISSUE TITLE
nREPL needs to be bumped

### ISSUE THREAD

**Issue by claj** [luminus-framework/luminus-nrepl#7]
A question was raised on https://clojureverse.org/t/nrepl-creates-thousands-of-threads-app-crashes/6527 where the root cause probably was that luminus-nrepl relies on an older version of nrepl with unfixed bugs, which only manifested itself in the uberjar (I _guess_ the tooling supplied a more recent version of nrepl in development which hid the problem). I have never used `luminus-nrepl` but I hope this still is helpful given that someone actually experienced a subtle problem with outdated dependencies using it.

**Comment by yogthos** [comment]
Thanks for the heads up, just pushed `0.1.7` to Clojars with updated dependencies.
